### ISSUE TITLE
ResolutionFolder=__SOURCE_DIRECTORY__ broken between dotnet 5.0.203 and 5.0.300

### ISSUE THREAD

**Issue by graydon** [fsprojects/FSharp.Data#1384]
With a random json file `t.json` in the current working directory, the following file works on dotnet 5.0.203:

```
#r "nuget: FSharp.Data"
open FSharp.Data
type t = JsonProvider<"t.json", ResolutionFolder=__SOURCE_DIRECTORY__>
```

On dotnet 5.0.300 it fails with the following message:

```
bad.fsx(3,50): error FS3045: Invalid static argument to provided type. Expected an argument of kind 'string'.
```

It can be worked around with the following:

```
#r "nuget: FSharp.Data"
open FSharp.Data
[<Literal>]
let path = __SOURCE_DIRECTORY__ + "/t.json"
type t = JsonProvider<path>
```

or

```
#r "nuget: FSharp.Data"
open FSharp.Data
[<Literal>]
let dir = __SOURCE_DIRECTORY__
type t = JsonProvider<"t.json", ResolutionFolder=dir>
```

So my guess is that `__SOURCE_DIRECTORY__` was implicitly marked as `[<Literal>]` in 5.0.203 but no longer in 5.0.300; in any case the first test is what the [docs use as examples](https://fsprojects.github.io/FSharp.Data/library/JsonProvider.html) and it no longer works, so something should probably be fixed.

**Comment by cartermp** [comment]
See here for more info: https://github.com/dotnet/fsharp/issues/11610

Nobody's investigated yet (3-day weekend, baby!) so I won't close this issue or the other one just yet. But once it does get investigated we'll resolve it one way or another.

**Comment by curr3nt** [comment]
Hello guys,

First of all, I am sorry for an unrelated question.

When our F# project code did not compile on a new environment because of `__SOURCE_DIRECTORY__` change, my first instinct was to replace it with a manually written path:
```
type NotWorking = JsonProvider<"file.json", ResolutionFolder = __SOURCE_DIRECTORY__, InferTypesFromValues = false>
```
->
``` 
type NotWorking = JsonProvider<"file.json", ResolutionFolder = @"C:\path\to\file\", InferTypesFromValues = false>
```
Unfortunately, this did not help, as code was still not compiling. However, it was showing a different error:
```
error FS1109: A reference to the type 'FSharp.Data.JsonProvider,Sample="file.json",ResolutionFolder="C:\\path\\to\\file\\",InferTypesFromValues="False"' in assembly 'FSharp.Data' was found, but the type could not be found in that assembly
```
This confused me quite a lot. After a colleague found this issue, we have settled with a second workaround that @graydon proposed. Thank you for the help.

However, I still wanted to understand why my quick fix did not work. I have realized that the problem was in **the last backward** slash. Once I removed it, code finally compiled. But, if I just set `InferTypesFromValues` to `true`, code compiles as well:
```
type Works = JsonProvider<"file.json", ResolutionFolder = @"C:\path\to\file\", InferTypesFromValues=true>
```
This behavior looks strange to me.

All in all, I think this is a minor issue that can be easily avoided. Still, if there is an explanation for this behavior, I would be very grateful to know (me being stupid is also an option 😃).

**Comment by cartermp** [comment]
Sorry for not updating on this end. This can be closed, as it's a core F# compiler issue and not an issue with this package: https://github.com/dotnet/fsharp/issues/11610

It has been fixed here: https://github.com/dotnet/fsharp/pull/11633

We're currently trying to figure out the best release channel for it.
